# Generated by Django 3.0.4 on 2020-03-21 07:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mileservice', '0002_auto_20200318_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pruegel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('geschlagen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='geschlagen', to='mileservice.Trinker')),
                ('schlaeger', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='schlaeger', to='mileservice.Trinker')),
            ],
        ),
    ]
