# Generated by Django 3.0.4 on 2020-03-21 14:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mileservice', '0004_auto_20200321_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Busfahrt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='bier',
            name='trinker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biere', to='mileservice.Trinker'),
        ),
        migrations.CreateModel(
            name='Bussitzer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_at', models.DateTimeField()),
                ('fahrer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mileservice.Trinker')),
                ('fahrt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mileservice.Busfahrt')),
            ],
        ),
    ]
