# Generated by Django 3.0.4 on 2020-03-21 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mileservice', '0005_auto_20200321_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bussitzer',
            name='answered_at',
        ),
        migrations.AddField(
            model_name='bussitzer',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
